import '../models/smart_home_models.dart';

const List<SmartDevice> seedDevices = [
  SmartDevice(
    id: 1,
    name: 'Smart Lamp',
    room: 'Dining Room',
    kind: 'Light',
    svgAsset: 'on_light',
    imageAsset: 'light-bulbs.png',
    isOn: true,
    intensity: 80,
    targetValue: 80,
    usageToday: 1.8,
    usageWeek: 11.4,
    usageMonth: 48.0,
    colorLabel: 'Warm White',
    schedules: [
      DeviceSchedule(
        label: 'Dinner mood',
        days: 'Mon Wed Fri',
        from: '7:00 pm',
        to: '10:30 pm',
      ),
      DeviceSchedule(
        label: 'Cleaning',
        days: 'Sat',
        from: '9:00 am',
        to: '11:00 am',
      ),
    ],
  ),
  SmartDevice(
    id: 2,
    name: 'Air Conditioner',
    room: 'Living Room',
    kind: 'AC',
    svgAsset: 'ac',
    imageAsset: 'air-conditioner.png',
    isOn: true,
    intensity: 72,
    targetValue: 21,
    usageToday: 4.6,
    usageWeek: 27.8,
    usageMonth: 119.0,
    schedules: [
      DeviceSchedule(
        label: 'Evening comfort',
        days: 'Daily',
        from: '6:00 pm',
        to: '11:00 pm',
      ),
    ],
  ),
  SmartDevice(
    id: 3,
    name: 'Bedroom Lamp',
    room: 'Bedroom',
    kind: 'Light',
    svgAsset: 'on_light',
    imageAsset: 'bg_lamp.png',
    isOn: false,
    intensity: 40,
    targetValue: 40,
    usageToday: 0.7,
    usageWeek: 4.1,
    usageMonth: 16.2,
    colorLabel: 'Cool White',
    schedules: [
      DeviceSchedule(
        label: 'Wake-up light',
        days: 'Mon Tue Wed Thu Fri',
        from: '6:30 am',
        to: '7:15 am',
      ),
    ],
  ),
  SmartDevice(
    id: 4,
    name: 'Television',
    room: 'Living Room',
    kind: 'TV',
    svgAsset: 'tv',
    imageAsset: 'living-room.png',
    isOn: true,
    intensity: 55,
    targetValue: 55,
    usageToday: 2.2,
    usageWeek: 13.0,
    usageMonth: 51.4,
    schedules: [
      DeviceSchedule(
        label: 'Kids time',
        days: 'Fri Sat',
        from: '4:00 pm',
        to: '7:00 pm',
      ),
    ],
  ),
  SmartDevice(
    id: 5,
    name: 'Bedroom AC',
    room: 'Bedroom',
    kind: 'AC',
    svgAsset: 'ac',
    imageAsset: 'air-conditioner.png',
    isOn: false,
    intensity: 65,
    targetValue: 22,
    usageToday: 1.1,
    usageWeek: 8.3,
    usageMonth: 34.6,
    schedules: [
      DeviceSchedule(
        label: 'Night sleep',
        days: 'Daily',
        from: '11:00 pm',
        to: '5:00 am',
        enabled: false,
      ),
    ],
  ),
  SmartDevice(
    id: 6,
    name: 'Kitchen Light',
    room: 'Kitchen',
    kind: 'Light',
    svgAsset: 'on_light',
    imageAsset: 'L_light.png',
    isOn: true,
    intensity: 68,
    targetValue: 68,
    usageToday: 1.3,
    usageWeek: 8.9,
    usageMonth: 36.8,
    colorLabel: 'Soft Yellow',
    schedules: [
      DeviceSchedule(
        label: 'Breakfast prep',
        days: 'Daily',
        from: '6:00 am',
        to: '8:00 am',
      ),
    ],
  ),
];

const List<UsagePoint> weeklyUsageSeed = [
  UsagePoint(label: 'Mon', value: 8),
  UsagePoint(label: 'Tue', value: 10),
  UsagePoint(label: 'Wed', value: 7),
  UsagePoint(label: 'Thu', value: 12),
  UsagePoint(label: 'Fri', value: 11),
  UsagePoint(label: 'Sat', value: 9),
  UsagePoint(label: 'Sun', value: 6),
];
